language: generic
dist: bionic

install:
  # Newer tools
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # spell
  - apt-cache search spell
  - sudo apt install spell
  # proselint
  - sudo pip install proselint
  # pandoc
  - sudo apt install pandoc 
  # imagemagick
  - sudo apt install imagemagick
  # PDF creation
  - sudo apt install texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-extra-utils texlive-humanities texlive-full texlive-games texlive-pictures texlive-science texlive-xetex ktikz
  # No: pgf

script:
  # proselint
  - proselint $(find | grep .*\.md) | egrep -v "curly_quotes" || true
  # Build article
  - make

