language: R
cache: packages

r_packages:
  - dplyr
  - gh
  - ggplot2
  - xtable

r_github_packages:
  - ropensci/spelling

script:
  - echo "Stub"
  #- make

after_script:
  #- Rscript -e 'spelling::spell_check_files("introduction.tex", ignore = readLines("inst/WORDLIST"))'
  # Same, but gives an error if spellcheck fails
  #- spelling_errors=$(Rscript -e 'spelling::spell_check_files("introduction.tex", ignore = readLines("inst/WORDLIST"))') ; [ "$spelling_errors" == "No spelling errors found." ]

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

after_success:
  # Download thesis
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

